name: All Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'npm'
        
    # Cache is already handled by actions/setup-node with cache: 'npm'

    - name: Install dependencies
      run: npm ci
      
    - name: Create .secrets directory
      run: mkdir -p .secrets
      
    - name: Create GitHub credentials file
      run: |
        echo "module.exports = {" > .secrets/github.js
        echo "  token_model: \"${{ secrets.GH_TOKEN }}\"," >> .secrets/github.js
        echo "  token: \"${{ secrets.GH_TOKEN }}\"," >> .secrets/github.js
        echo "  token_new: \"${{ secrets.GH_TOKEN }}\"" >> .secrets/github.js
        echo "};" >> .secrets/github.js
        
    - name: Run unit tests
      run: npm run test:unit
      
    - name: Run integration tests
      run: npm run test:integration
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        
    - name: Run E2E tests
      run: npm run test:e2e
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        TEST_ISSUE_NUMBER: 1 # Use issue #1 for tests
        CI: false # This will prevent the CI check from skipping tests
        
    - name: Run model tests with mock
      run: npm run test:models:mock
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}